# Generated by Django 4.0.3 on 2022-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item_subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='method',
            field=models.CharField(blank=True, default='card', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
