# Generated by Django 3.2.7 on 2021-09-13 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_listings', to='auctions.categories'),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_listing_id', to='auctions.bids'),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starting_listing_id', to='auctions.bids'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='winning_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_listing_id', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
