# Generated by Django 3.2.7 on 2022-01-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pp_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pp_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
