# Generated by Django 4.0.3 on 2022-04-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_invoice_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='auctions.listing'),
        ),
    ]
