# Generated by Django 3.2.7 on 2022-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_image_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
