# Generated by Django 3.2.7 on 2021-09-14 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210913_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.AddField(
            model_name='listing',
            name='Comment',
            field=models.ManyToManyField(to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='Comment',
            field=models.ManyToManyField(to='auctions.Comment'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_Bid', to='auctions.listing')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_Bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_listing_id', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starting_listing_id', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winning_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_listing_id', to='auctions.bid'),
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
