# Generated by Django 3.2.7 on 2021-09-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210913_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Comment',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
