# Generated by Django 3.2.7 on 2021-09-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210913_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winning_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bids',
            field=models.ManyToManyField(blank=True, to='auctions.Bid'),
        ),
    ]
