# Generated by Django 4.0.3 on 2022-04-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winning_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
