# Generated by Django 4.0.3 on 2022-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_invoice_item_subtotal_invoice_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
