# Generated by Django 3.2.7 on 2021-11-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Comment',
        ),
    ]
