# Generated by Django 3.2.7 on 2021-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_listing_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
