# Generated by Django 3.2.7 on 2021-11-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20211126_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shipping',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
