# Generated by Django 3.2.7 on 2022-01-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='/static/auctions/auctions/images/gavel_icon.png', max_length=100),
        ),
    ]
