# Generated by Django 3.2.7 on 2021-12-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
