# Generated by Django 3.2.7 on 2021-12-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_rename_notifications_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='template',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, default='primary', help_text='the Bootstrap alert type', max_length=50),
        ),
    ]
