# Generated by Django 3.2.7 on 2022-01-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20220123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.listing'),
        ),
    ]
