# Generated by Django 3.2.7 on 2022-01-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_user_image_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.listing'),
        ),
    ]
