# Generated by Django 3.2.7 on 2022-01-27 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_user_image_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('starting_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('lifespan', models.IntegerField(blank=True, default=1, help_text='days until listing expires.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
