# Generated by Django 3.2.7 on 2022-01-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_templisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Image',
            new_name='UserImage',
        ),
    ]
