# Generated by Django 3.2.7 on 2022-01-28 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_rename_user_image_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='temp_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.templisting'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
