# Generated by Django 3.2.7 on 2022-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_listing_winning_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='users_watchlist', to='auctions.Listing'),
        ),
    ]
