# Generated by Django 3.2.7 on 2022-01-31 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20220127_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.listing'),
        ),
    ]
