# Generated by Django 3.2.7 on 2022-02-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_userimage_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='temp_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.templisting'),
        ),
    ]
