# Generated by Django 3.2.7 on 2022-01-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20220105_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlisting',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testlisting',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testuser',
            name='watching',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
