# Generated by Django 3.2.7 on 2022-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_userimage_temp_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='templisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='templisting',
            name='lifespan',
            field=models.IntegerField(blank=True, default=30, help_text='days until listing expires.', null=True),
        ),
    ]
