# Generated by Django 3.2.7 on 2022-02-11 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20220211_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templisting',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
