# Generated by Django 3.2.7 on 2022-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_testlisting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlisting',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.TestUser'),
        ),
    ]
