# Generated by Django 3.2.7 on 2022-01-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_alter_testlisting_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlisting',
            name='watchers',
        ),
        migrations.AlterField(
            model_name='testlisting',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_listings', to='auctions.testuser'),
        ),
    ]
