# Generated by Django 3.2.7 on 2022-01-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20220105_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='watching',
            field=models.ManyToManyField(blank=True, to='auctions.TestListing'),
        ),
    ]
