# Generated by Django 3.2.7 on 2022-01-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20220105_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lifespan',
            field=models.IntegerField(default=1),
        ),
    ]
