# Generated by Django 3.2.7 on 2022-01-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_alter_listing_lifespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lifespan',
            field=models.IntegerField(default=1, help_text='days until listing expires.'),
        ),
    ]
