# Generated by Django 3.2.7 on 2022-01-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auto_20220106_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='page',
            field=models.CharField(default='index', help_text='Defines on which page the notification should appear.', max_length=50),
        ),
    ]
