# Generated by Django 3.2.7 on 2022-01-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20220107_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.comment'),
        ),
    ]
