# Generated by Django 3.2.7 on 2022-01-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_alter_comment_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', upload_to='profile_pictures/%Y/%m/%d/', width_field='width'),
        ),
    ]
