# Generated by Django 3.2.7 on 2022-01-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pp_height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pp_width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, height_field='pp_height', upload_to='profile_pictures/%Y/%m/%d/', width_field='pp_width'),
        ),
    ]
