# Generated by Django 3.2.7 on 2022-01-14 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_auto_20220114_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pp_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pp_width',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='pp_height', upload_to='profile_pictures/%Y/%m/%d/', width_field='pp_width')),
                ('pp_width', models.IntegerField(blank=True)),
                ('pp_height', models.IntegerField(blank=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
