# Generated by Django 3.2.7 on 2022-01-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_auto_20220114_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, height_field='pp_height', upload_to='%Y/%m/%d/', width_field='pp_width'),
        ),
    ]
